# Gitleaks Security Scan Workflow
# 
# This reusable workflow runs Gitleaks security scans to detect exposed secrets,
# API keys, and sensitive information in your repositories. It uses the official
# gitleaks-action and automatically uploads results to GitHub's Security tab.
#
# Usage:
#
# jobs:
#   gitleaks-scan:
#     uses: salemove/glia-security-workflows/.github/workflows/secrets-scan.yaml@master
#     secrets: inherit
#

name: Secrets Scan

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to gitleaks config file (optional)'
        required: false
        type: string
        default: ''
      enable-comments:
        description: 'Enable PR comments on findings'
        required: false
        type: boolean
        default: true
      enable-summary:
        description: 'Enable job summary'
        required: false
        type: boolean
        default: true
      enable-upload-artifact:
        description: 'Enable SARIF artifact upload'
        required: false
        type: boolean
        default: true
      gitleaks-version:
        description: 'Gitleaks version to use (e.g., 8.15.3 or latest)'
        required: false
        type: string
        default: ''  # latest
      fail-on-detection:
        description: 'Whether to fail the workflow when secrets are detected'
        required: false
        type: boolean
        default: false  # Default to non-blocking

jobs:
  gitleaks-scan:
    name: Run Gitleaks Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: read
      security-events: write
      actions: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: salemove/gitleaks-action@master  # v2.3.9 with Merge Queue support
        continue-on-error: true  # Don't fail the step if secrets are found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_CONFIG: ${{ inputs.config-path }}
          GITLEAKS_ENABLE_COMMENTS: ${{ inputs.enable-comments }}
          GITLEAKS_ENABLE_SUMMARY: ${{ inputs.enable-summary }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: ${{ inputs.enable-upload-artifact }}
          GITLEAKS_VERSION: ${{ inputs.gitleaks-version }}

      - name: Conditional failure
        if: inputs.fail-on-detection && steps.gitleaks.outcome == 'failure'
        run: |
          echo "Failing workflow due to secret detection (fail-on-detection=true)"
          exit 1
