# Snyk API Import Sync Workflow
#
# This reusable workflow synchronizes GitHub repositories with Snyk for security scanning.
# It uses the snyk-api-import tool to import repositories into a specified Snyk organization.
#
# Usage:
#
# jobs:
#  sync-snyk-projects:
#    uses: salemove/glia-security-workflows/.github/workflows/snyk-projects-sync.yaml@<commit_hash>
#    secrets:
#      SNYK_SYNC_TOKEN: ${{ secrets.SNYK_SYNC_TOKEN }}
#      GITHUB_PAT: ${{ secrets.SNYK_GITHUB_SYNC_TOKEN }}
#

name: Snyk API Import Sync

on:
  workflow_call:
    inputs:
      snyk-products:
        description: 'Comma-separated list of Snyk products to scan for'
        required: false
        type: string
        default: 'container,open-source,iac'
      snyk-log-path:
        description: 'Path for Snyk logs'
        required: false
        type: string
        default: '/tmp/snyk-log'
    secrets:
      SNYK_SYNC_TOKEN:
        description: 'Snyk API token'
        required: true
      GITHUB_PAT:
        description: 'GitHub Personal Access Token with repo scope'
        required: true

defaults:
  run:
    shell: bash -Euo pipefail {0}

jobs:
  snyk-api-import-sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3
        with:
          node-version: 20

      - name: Install Snyk API Import
        run: npm install snyk-api-import@2.21.6 -g

      - name: Run Snyk API Import Sync
        shell: bash
        run: |
          set -euo pipefail
          # Convert comma-separated list to multiple --snykProduct arguments
          PRODUCTS="${{ inputs.snyk-products }}"
          PRODUCT_ARGS=""
          
          # Create separate --snykProduct arguments for each product
          IFS=',' read -ra PRODUCT_ARRAY <<< "$PRODUCTS"
          for product in "${PRODUCT_ARRAY[@]}"; do
              PRODUCT_ARGS="$PRODUCT_ARGS --snykProduct=$product"
          done
          
          echo "Starting Snyk API Import with org: ${SNYK_ORGANIZATION_ID}"
          # Run command with properly formatted product arguments
          snyk-api-import sync --orgPublicId=${SNYK_ORGANIZATION_ID} --source=github $PRODUCT_ARGS
        env:
          DEBUG: '*snyk*'
          SNYK_TOKEN: ${{ secrets.SNYK_SYNC_TOKEN }}
          SNYK_LOG_PATH: ${{ inputs.snyk-log-path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          SNYK_ORGANIZATION_ID: ${{ vars.SNYK_ORGANIZATION_ID }}

      - name: Upload Snyk logs as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        if: always()
        with:
          name: snyk-sync-logs
          path: ${{ inputs.snyk-log-path }}
          retention-days: 7
